version: "2.1"

services:
  frontend:
    build: ./frontend/
    ports:
      - 80:80
      - 443:443
  api:
    build: ./api/
    depends_on:
      - db
  db:
    image: "mongo:4.0.5"
    ports:
      - 27016:27017
    volumes:
      - ./data/db:/data/db
      - ./data/001_users:/docker-entrypoint-initdb.d/001_users.js:ro
    restart: always
    env_file:
      - ./data/mongo.env
